import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Duck ERP School - Duck',
    description: 'Generated by create next app',
}

const DuckErpSchool = () => {
    return (
        <div>
            <p>Duck ERP School //// aditional</p>
        </div>
    );
};

export default DuckErpSchool;