import ConatctSection from '@/components/Contact/ConatctSection';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: 'Contact Us - Duck',
    description: 'Generated by create next app',
}


const ContactUs = () => {
    return (
        <div>
            <div className="flex justify-center">
                <p className="text-center">Contact Us</p>
                <ConatctSection />
            </div>
        </div>
    );
};

export default ContactUs;