import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Contact Us - Duck',
    description: 'Generated by create next app',
}


const ContactUs = () => {
    return (
        <div className='red ' >
            <p>Contact Us</p>
        </div>
    );
};

export default ContactUs;