import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Duck ERP Retail - Duck',
    description: 'Generated by create next app',
}

const DuckErpRetail = () => {
    return (
        <div>
            <p>Duck ERP Retail https://www.dhru.com/products/dhru-erp/retail</p>
        </div>
    );
};

export default DuckErpRetail;