import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Duck ERP Restaurant - Duck',
    description: 'Generated by create next app',
}

const DuckErpEcommerce = () => {
    return (
        <div>
            <p>duck erp restaurant https://www.dhru.com/products/dhru-ecommerce</p>
        </div>
    );
};

export default DuckErpEcommerce;