import { Metadata } from 'next';
import React from 'react';


export const metadata:Metadata = {
    title: 'Duck Fusion - Duck',
    description: 'Generated by create next app',
}


const DuckFusion = () => {
    return (
            // should follow >> https://www.dhru.com/products/dhru-fusion
        <div>
            <p>duck fusion  https://www.dhru.com/products/dhru-fusion</p>
        </div>
    );
};

export default DuckFusion;