import ServiceSection from '@/components/Service/ServiceSection';
import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Services - Duck',
    description: 'Generated by create next app',
}

const Services = () => {
    return (
        <div className=' ' >
            <p>Services</p>
            <ServiceSection />
        </div>
    );
};

export default Services;