import './globals.css'
import { Urbanist } from 'next/font/google'

const urbanist = Urbanist({ subsets: ['latin'], weight:['400', '700'] })

export const metadata = {
  title: 'Home - Duck',
  description: 'Generated by create next app',
}

/// do not work here

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        {children}
      </body>
    </html>
  )
}
