import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Duck Ecommerce - Duck',
    description: 'Generated by create next app',
}

const DuckEcommerce = () => {
    return (
        <div>
            <p>duck ecommerce https://www.dhru.com/products/dhru-ecommerce</p>
        </div>
    );
};

export default DuckEcommerce;