import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Duck ERP Service Center - Duck',
    description: 'Generated by create next app',
}

const DuckErpService = () => {
    return (
        <div>
            <p>Duck ERP service https://www.dhru.com/products/dhru-erp/servicecenter</p>
        </div>
    );
};

export default DuckErpService;