import { Metadata } from 'next';
import React from 'react';

export const metadata:Metadata = {
    title: 'Duck Wallet - Duck',
    description: 'Generated by create next app',
}

const DuckWaller = () => {
    return (
        <div>
            <p>Duck Waller https://www.dhru.com/products/dhru-wallet</p>
        </div>
    );
};

export default DuckWaller;